# Generated by Django 2.0.1 on 2020-03-24 06:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default='', max_length=64)),
                ('Cnic', models.CharField(default='', max_length=13)),
                ('description', models.CharField(default='', max_length=400)),
                ('date_of_birth', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('whattsapp', models.CharField(default='', max_length=25)),
                ('phone', models.IntegerField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(upload_to='proflie/profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
