# Generated by Django 2.2.5 on 2019-12-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fb_id',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='linkden_id',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='twiter_id',
            field=models.URLField(),
        ),
    ]
