# Generated by Django 2.2.5 on 2019-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.TextField(max_length=350)),
                ('info', models.TextField(max_length=350)),
                ('danger', models.TextField(max_length=350)),
                ('warning', models.TextField(max_length=350)),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('detail', models.TextField()),
            ],
        ),
    ]
