# Generated by Django 2.2.5 on 2019-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
