# Generated by Django 2.2.5 on 2019-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_jobform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobform',
            name='image',
            field=models.ImageField(upload_to='jobs/%Y/%m/%d'),
        ),
    ]
