# Generated by Django 2.0.3 on 2019-12-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191221_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobform',
            name='image',
            field=models.ImageField(upload_to='jobs'),
        ),
    ]
