# Generated by Django 2.0.3 on 2019-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191225_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobform',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
