# Generated by Django 2.0.3 on 2019-12-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_usercreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='password2',
        ),
    ]
