# Generated by Django 2.0.3 on 2019-12-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_usercreation_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='courses/%Y/%m/%d')),
                ('offer', models.BooleanField(default=False)),
                ('instructor', models.CharField(max_length=64)),
            ],
        ),
    ]
