# Generated by Django 2.0.3 on 2019-12-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_home_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_course',
            name='offer',
            field=models.BooleanField(),
        ),
    ]
