# Generated by Django 2.0.3 on 2019-12-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20191228_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_course',
            old_name='offer',
            new_name='Free',
        ),
    ]
