# Generated by Django 2.0.1 on 2020-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20191228_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_course',
            name='Price',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
