# Generated by Django 2.0.1 on 2020-01-22 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_home_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_course',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
