# Generated by Django 2.0.1 on 2020-01-22 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_home_course_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_course',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=datetime.datetime.now),
        ),
    ]
