# Generated by Django 2.0.1 on 2020-01-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200122_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_course',
            name='Seats',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='home_course',
            name='course_outline',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AddField(
            model_name='home_course',
            name='objectives',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='home_course',
            name='pre_requirements',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
