# Generated by Django 2.0.1 on 2020-01-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200123_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_course',
            name='course_outline',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='home_course',
            name='objectives',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='home_course',
            name='pre_requirements',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
