# Generated by Django 2.0.1 on 2020-03-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200128_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_No', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('video', models.FileField(upload_to='course/videos')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.home_course')),
            ],
        ),
    ]
