# Generated by Django 2.0.1 on 2020-03-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
